"""
AI小说拆书系统 - 数据模型模块
"""
from .database import Base, engine, get_session, init_db
from .models import Book, ProcessingTask, Chapter, Outline, ErrorLog
from .schemas import (
    APIResponse,
    ErrorResponse,
    BookCreate,
    BookSummary,
    BookDetail,
    UploadBookData,
    UploadBookResponse,
    BookListData,
    BookListResponse,
    BookDetailResponse,
    DeleteBookResponse,
    OutlineTreeNode,
    OutlineTreeData,
    OutlineTreeResponse,
    ChapterOutlineContent,
    GenericOutlineContent,
    OutlineDetailData,
    OutlineDetailResponse,
    CopyOutlineData,
    CopyOutlineResponse,
    StageProgress,
    TaskStatusData,
    TaskStatusResponse,
    TaskErrorItem,
    TaskErrorsData,
    TaskErrorsResponse,
    WebSocketProgressPayload,
    WebSocketOutlineUpdatePayload,
    WebSocketErrorPayload,
    WebSocketCompletedPayload,
)

__all__ = [
    # 数据库
    "Base", "engine", "get_session", "init_db",
    # ORM模型
    "Book", "ProcessingTask", "Chapter", "Outline", "ErrorLog",
    # Pydantic模型
    "APIResponse",
    "ErrorResponse",
    "BookCreate",
    "BookSummary",
    "BookDetail",
    "UploadBookData",
    "UploadBookResponse",
    "BookListData",
    "BookListResponse",
    "BookDetailResponse",
    "DeleteBookResponse",
    "OutlineTreeNode",
    "OutlineTreeData",
    "OutlineTreeResponse",
    "ChapterOutlineContent",
    "GenericOutlineContent",
    "OutlineDetailData",
    "OutlineDetailResponse",
    "CopyOutlineData",
    "CopyOutlineResponse",
    "StageProgress",
    "TaskStatusData",
    "TaskStatusResponse",
    "TaskErrorItem",
    "TaskErrorsData",
    "TaskErrorsResponse",
    "WebSocketProgressPayload",
    "WebSocketOutlineUpdatePayload",
    "WebSocketErrorPayload",
    "WebSocketCompletedPayload",
]
